language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tgdocker2019/docer-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tgdocker2019/docer-react npm run test
