language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tgdocker2019/docer-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tgdocker2019/docer-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-776925283001"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
